### ISSUE TITLE
Show / hide animations are not smooth on Chrome / Android

### ISSUE THREAD

**Issue by dioslaska** [acidb/mobiscroll#345]
Tested on the new Chrome 44 / Android 5.1.1

**Comment by shamank** [comment]
It's a shame because the animation is ruining the "presentation" of such a good and robust component, specially in mobile. 

I've realized that it's because the amount of elements it has to move at the same time. The calendar, that has a lot of elements, is one of the heaviest, so the animation performance is very poor on mobile (even in fast devices like Nexus 5 with Android 5.1.1). However, a component like a simple scroller is animated with a good (+/-) performance.

I've been thinking about this and the more elegant and efficient solution is to perform the animation on a simple element (a facade element, like a div with some nice blured image or fake elements like Facebook shows when loading the newsfeed) and after animation is done you can fadeIn the real component, replacing the facade. That way is still elegant and animation will perform excelent for all devices, even slow ones.

I would include this as an option at least.

PS: This is the "facade" element from Facebook I'm refering to:
![facade](https://cloud.githubusercontent.com/assets/819192/9764126/a2e4de1e-56e3-11e5-8a8d-f98f9a4b71a9.png)

**Comment by allenchengren** [comment]
v 2.17.2 animations are not smooth on Android

**Comment by kovlex** [comment]
Continuous improvements were made regarding animations. Current version is 4.2.3. Closing issue.
