### ISSUE TITLE
Forms' Select not prepared well for accessibility

### ISSUE THREAD

**Issue by stehlo** [acidb/mobiscroll#403]
When Forms' Select is displaying options, those options do not use `aria-labelledby`.

```HTML
<div id="lang_hd" class="mbsc-divider mbsc-padding" data-l10n="Language">Language</div>
<div style="display: none;">
    ...
    <span id="lne_vi">Vietnamese</span>
    <span id="lne_ar">Arabic</span>
    <span id="lne_zh-TW">Chinese (Traditional)</span>
</div>
<select id="lang" name="lang" aria-labelledby="lang_hd" class="mbsc-control mbsc-control-ev">
    ...
    <option id="lang_vi" value="vi" aria-labelledby="lang_hd lang_vi lne_vi">Tiếng việt</option>
    <option id="lang_ar" value="ar" aria-labelledby="lang_hd lang_ar lne_ar">العربية</option>
    <option id="lang_zh-TW" value="zh-TW" aria-labelledby="lang_hd lang_zh-TW lne_zh-TW">台灣話</option>
</select>
````

Whatever is pointed to by `aria-labelledby` is not being read by TalkBack.

It seems to me that the way you construct the overlay selector, it doesn't transport those attributes.

This issue doesn't apply to other Forms' controls.

**Comment by stehlo** [comment]
On top of that, the `aria-labelledby` of the `select` tag itself is not being transported onto the newly created `input.mbsc-control` which displays the selected value.

```HTML
<select id="lang" name="lang" aria-labelledby="lang_hd" class="mbsc-control mbsc-control-ev">
    ...
</select>
<input tabindex="-1" type="text" class="mbsc-control mbsc-control-ev" readonly="">
<span class="mbsc-select-ic mbsc-ic mbsc-ic-arrow-down5"></span>
```

The problem is that such a resulting external element is being read by TalkBack as "[value] popup button" without any relation to the actual `select` and its `label`.

**Comment by dioslaska** [comment]
This seems rather a TalkBack + Chrome issue.
The same can be reproduced on a select without initializing the Mobiscroll Form on it. Nor the normal label, neither the aria-label or aria-labelledby is not being read by TalkBack.
This seems like a similar issue: https://bugs.chromium.org/p/chromium/issues/detail?id=630862

About the input created by Mobiscroll: there is no interaction with it, since the native select element is placed over it with opacity 0, so there's no need to copy the aria attributes. It also has tabindex="-1" to prevent focus from keyboard as well.

**Comment by stehlo** [comment]
My apologies for not commenting earlier. Just yesterday, I had to replace the Select with a Listview.

In itself, it was a bit of task, because the Form component had to be initialised within the Listview component, which created rather odd looking structure (it had to be taken care for by CSS adjustments).

However, as such, it resolved the issue with accessibility (and also with complex tags for "options").
