### ISSUE TITLE
Calendar clear button throws an error

### ISSUE THREAD

**Issue by szily20** [acidb/mobiscroll#432]
This issue occurs when a month/year was navigated on the calendar and after that the clear button was pressed.  

It gives a `Uncaught TypeError: Cannot read property 'html' of undefined` error.

**Comment by AckerApple** [comment]
I am subscribed to this issue. I am original reporter. The issue seems to occur anytime I tap "clear" and not just as you say "when a month/year was navigated".

**Comment by AckerApple** [comment]
It seems you are correct about navigating month/year and then tapping "clear". No wonder I've driven myself nuts trying to pin down the issue

**Comment by dioslaska** [comment]
Fixed in 3.2.4

**Comment by AckerApple** [comment]
How elegantly timed with my paid subscription ending, that you release the fix for an issue I reported.

Ironic, coincidence, conspiracy theory? It's just what one gets with the ol' paid platform.

Hey feel free to use any of my free code: https://www.npmjs.com/~ackerapple

I also have Angular4 mobiscroll wrapper if it inspires you: https://www.npmjs.com/package/ack-angular-mobiscroll

Yah know, maybe out of good gesture, ya'll could gift me v3.2.4 . Think about it.

**Comment by dioslaska** [comment]
Hi Acker, I extended the maintenance period until 23rd Sept, so you should be able to download v3.2.4 as well.
Also, thanks for the links, we will take a look. Meanwhile our own Angular4 implementation is now out of beta, you can download that as well.

**Comment by AckerApple** [comment]
What a very kind and fair gesture. Thank you much, appreciated much.

Reputation points go out to you guys for doing the right thing. I'll download what I need right away.

**Comment by AckerApple** [comment]
I got the files I needed. My plan is to try and coast without paying for Mobiscroll again. I strongly back the open source platform and it's in my head Mobiscroll belongs there.

Mobiscroll is the best calendar. You'd do the world and yourselves a lot good giving Mobiscroll away.
