### ISSUE TITLE
Range: possible bug onDayChange event

### ISSUE THREAD

**Issue by mattboschetti** [acidb/mobiscroll#455]
Component: Range
For: AngularJS (1.7)
Version: 4.4.2

Since I didn't find a way to prevent range selection spanning over invalid dates, I thought of checking if the selected dates were valid on the `onDayChange` event.

However I found that at the time the `onDayChange` event is triggered the underlying variable attached to the ng-model is not updated (_which on its own is a potential issue as it is difficult to update state in a parent component without resorting to 2 way data binding and other workarounds to get the data from user other events, [example use case](https://codepen.io/mattboschetti/pen/zMjrZg)_).

To circumvent this issue I decided to keep the start and end dates in separate variables, and setting them according to `event.selected` value sent by `onDayChange` event, so I could decide whether or not to cancel this selection.

First there is a discrepancy between the code and the documentation (https://docs.mobiscroll.com/angularjs/range#event-onDayChange). The documentation states that `event.selected` would be either `start` or `end`, however these values are set on `event.active` property instead.

Second issue is that whenever one selects a start date (ex: Nov-23) and for end date selects a prior date (ex: Nov-20), the `onDayChange` `event.active` is set to `end`. However observing the `onSetDate` `event.active`, you will notice that it set to `start`. Therefore I believe that the correct behavior for the `onDayChange` event should be setting `event.active` to `start`.

Check the console of this [pen](https://codepen.io/mattboschetti/pen/pQVvQB) after selecting the start date and then selecting an end date prior to the start.

**Comment by dioslaska** [comment]
Hi Matt, thanks for pointing out the documentation issues, we fixed the selected / active descriptions.

About the issues:

The model is not yet set in the `onDayChange` event, because it runs before the selection actually occurs, so this is expected behavior. The remark on the `active` being 'end' instead of 'start' in some cases is correct. Since the day selection only occurs after this event, the correction from 'end' to 'start' will run later in the cycle.

On the other hand, in the `onSetDate` event the selection is already done, however did not propagate yet into the model. To access the dates from your model, you will need to do that in the next digest cycle, this can be done by wrapping into a `$timeout`:

    onSetDate: (ev, inst) => {
        $timeout(() => console.log(self.selectedDates));
    }

My recommended approach would be something like this:

    onDayChange: (event, inst) => {
        if (event.active = 'end' && event.date > self.selectedDates[0]) {
            // check validity
            if (self.isValidRange(self.selectedDates[0], event.date)) {
                self.onSelect({
                  startDate: self.selectedDates[0],
                  endDate: event.date
                });
                return true;
            }
            return false;
        }
    }

Let me know if this makes sense!
