### ISSUE TITLE
Mobiscroll NPM Registry Not Found

### ISSUE THREAD

**Issue by n-glaz** [acidb/mobiscroll#518]
@mobiscroll/react on npm.mobiscroll.com appears to be down. Every version I try to fetch 404s out, and I get forbidden when attempting to get the root .com.

[Related forum post](https://forum.mobiscroll.com/t/is-mobiscrolls-npm-down/1648)

**Comment by jayeshkataria** [comment]
plus one

**Comment by chvrles** [comment]
Also experiencing this issue.

**Comment by mora260** [comment]
happens to me as well. Also can't login using their CLI. I got: 405 - HTTP verb used to access this page is not allowed.

**Comment by manojbavikati** [comment]
Same issue as well for us.

**Comment by kovlex** [comment]
Thanks for the reports! Should be fixed now. New tokens will be needed since the private npm registry had to be rebuilt internally.

In case of NPM, call a `mobiscroll login` in your application root folder (use your email address and password) followed by pushing the `.npmrc` into your repository.

In case of YARN call `mobiscroll logout` followed by a `mobiscroll config {framework}` to install the latest version or specify the exact version like `mobiscroll config {framework} --version 5.22.3`. This will take care of refreshing the tokens after which you can push the `yarnrc.yml` into your repository.

If for some reason this is not working, please share the exact version you are trying to install.

**Comment by ericmorentin** [comment]
@kovlex we are trying to install 4.10.10

"No matching version found for @mobiscroll/angular@4.10.10"

**Comment by dioslaska** [comment]
@ericmorentin Version 4.10.10 should work now as well.

**Comment by ericmorentin** [comment]
@dioslaska thank you!

**Comment by FireRageNL** [comment]
Hi! We're running into an issue installing Mobiscroll. We've generated a new token but now receive the following error when we install version 5.18.3 for angular.

`npm WARN tarball tarball data for @mobiscroll/angular@https://npm.mobiscroll.com/@mobiscroll%2fangular/-/angular-5.18.3.tgz (sha512-TsxfknN8KvA1Sv0oh5NF6KtosVosl/5+7lR3kX/MvRZ0LFnfrsnKRD7okV2liK4DCER5GfHylg0SKCU4ePAgpQ==) seems to be corrupted. Trying again.
npm ERR! code EINTEGRITY
npm ERR! sha512-TsxfknN8KvA1Sv0oh5NF6KtosVosl/5+7lR3kX/MvRZ0LFnfrsnKRD7okV2liK4DCER5GfHylg0SKCU4ePAgpQ== integrity checksum failed when using sha512: wanted sha512-TsxfknN8KvA1Sv0oh5NF6KtosVosl/5+7lR3kX/MvRZ0LFnfrsnKRD7okV2liK4DCER5GfHylg0SKCU4ePAgpQ== but got sha512-nArm4fW/2PZ2wFCJ4zDE+vojY77tvt1i+xLdsvdQ7IBK32A2X6HKwSaI0t3oq9uKf1SX9eCVrMkZdyNhJheJ3g==. (543495 bytes)
`

**Comment by dioslaska** [comment]
@FireRageNL Please try uninstalling the package and installing it again.

**Comment by FireRageNL** [comment]
@dioslaska Thanks! That fixed it :)
